### ISSUE TITLE
hi，您好！

### ISSUE THREAD

**Issue by hongyan007** [jiangqingbo/HyRefreshLayout-Android#1]
我在Reactnative源码编译的时候，遇到了如下的错误：怎么解决呢？ 
![image](https://cloud.githubusercontent.com/assets/8362319/19753635/e3437a74-9c38-11e6-975a-2a84775b722a.png)

**Comment by hongyan007** [comment]
我最近没有在研究Reactnative项目了，之后研究好了在与你联系，ok 。如果已经解决，请立刻给我打个电话，感激不尽。 18600412701

**Comment by jiangqingbo** [comment]
@DearDominic 最近没在研究Reactnative项目，之后研究好了在与你联系，ok。

**Comment by hongyan007** [comment]
OK  我已经成功了，如果有需要 我把代码上传
